orthographe
NextDom/nextdom-core pull request #1025
Opened 2019-04-08 00:20 UTC by noodom

- doublons pour status ? (il me manque le contexte) : "Remise à zéro des status du status des SI du scénario"

2019-04-08 08:50 UTC, cyrilphoenix71 approved these changes

2019-04-08 18:57 UTC, ColonelMoutarde approved these changes

2019-04-08 19:40 UTC, Gis70 requested changes
ligne 1318 mettre NextDom

2019-04-11 19:48 UTC, Sylvaner approved these changes
Changement fait

2019-04-11 19:49 UTC, merged