Fix april
NextDom/nextdom-core pull request #1031
Opened 2019-04-17 16:13 UTC by Sylvaner

https://github.com/NextDom/nextdom-core/issues/909
https://github.com/NextDom/nextdom-core/issues/914
https://github.com/NextDom/nextdom-core/issues/961
https://github.com/NextDom/nextdom-core/issues/997
https://github.com/NextDom/nextdom-core/issues/965

2019-04-17 17:24 UTC, Gis70 commented
965 et 961 OK

2019-04-18 11:51 UTC, ColonelMoutarde requested changes
On ne doit pas rajouter du style directement dans les vues.

2019-04-19 09:53 UTC, cyrilphoenix71 commented
@ColonelMoutarde pour les styles je suis en train de tous virer dans branche UI ;)

2019-04-20 08:35 UTC, Esso1-jeedom commented
#909 ok pour moi

2019-04-20 08:40 UTC, Esso1-jeedom approved these changes

2019-04-20 13:41 UTC, Sylvaner commented
Aléatoire du #965 corrigé, c'était l'évènement qui était sur le l'icone et pas le bouton

2019-04-20 19:24 UTC, Gis70 approved these changes
ok

2019-04-21 08:12 UTC, merged