use nextdom-core:test image instead of sylvaner's
NextDom/nextdom-core pull request #1056
Opened 2019-04-28 20:11 UTC by psycofdj

Use dockerhub auto-builded test image https://hub.docker.com/r/nextdom/nextdom-core/builds in travis build

2019-04-28 20:12 UTC, psycofdj commented
travis will fail until a commit on develop branch triggers the build of test base image

2019-04-30 07:04 UTC, ColonelMoutarde approved these changes

2019-05-01 12:06 UTC, Sylvaner commented
Lol colonel le commit à l'aveugle

2019-07-01 09:40 UTC, slobberbone commented
du coup si on sort tout ce qui est docker, cette PR comment on la reporte sur https://github.com/NextDom/nextdom-docker @psycofdj ?

2019-07-25 09:33 UTC, slobberbone requested changes
Nécessite une coopération avec @Sylvaner afin d'être sur de ne pas casser les tests.

2019-11-05 07:51 UTC, Sylvaner commented
C'est fait merci

2019-11-05 07:51 UTC, closed without merging