PR branche GUI
NextDom/nextdom-core pull request #1059
Opened 2019-04-29 21:43 UTC by cyrilphoenix71

Modifs :
- fix issue #1051
- fix issue #1022
- fix issue #940
- fix issue #817
- fix issue #937
- Rangements des controllers
- Nettoyage/Rangement/Optimisation CSS
- Mise en forme de modales + scission JS/CSS
- Ajout spinner d'attente personnalisé
- Adaptation automatique page old school jeedom en nextdom style

To test :
- Postinstall OBLIGATOIRE
- tester TOUT au maximum (backup/restore/pages/sauvegardes etc)
- Pour les issues, testées les puis commentez ok dans l'issue, cloturez si 3e commentaire

2019-05-01 09:37 UTC, psycofdj commented on src/Helpers/FileSystemHelper.php
> +                    'jquery.ui/jquery-ui-bootstrap/jquery-ui' => 'assets/css/vendors/jquery-ui-bootstrap/jquery-ui.css'
si je comprends bien *jquery-ui-bootstrap* ne s'installe pas via composer
est-ce qu'on pourrait pas malgré tout l'installer dans notre dossier `./vendor` ? par exemple en tant qu'etape du `gen_assets.sh` 

ca me fait bizarre de multiple les dossiers vendor dans le source-tree

2019-05-01 09:45 UTC, psycofdj requested changes
Une traduction qui sembler manquer sur l'écran d'accueil (apres *postinst* et *firstUse*)

![image](https://user-images.githubusercontent.com/1496191/57012379-77619c00-6c06-11e9-928d-2fba56eb9c99.png)

>> DONE

2019-05-01 09:47 UTC, psycofdj reviewed
(peut etre pas lié à la PR)
Il y a des sauts de ligne qui trainent dans l'output de restore backup:

![image](https://user-images.githubusercontent.com/1496191/57012456-eb9c3f80-6c06-11e9-9fc0-737e0ba36beb.png)

2019-05-01 09:56 UTC, psycofdj requested changes
erreur sur les pages de market jeedom et nextdom:

![image](https://user-images.githubusercontent.com/1496191/57012716-2357b700-6c08-11e9-9084-3dfb5a0b1ea0.png)

>> DONE

2019-05-01 10:02 UTC, psycofdj requested changes
lorsqu'on modifie sa photo de profile, il faut regarder 2 fois la page avant de voir apparaître le modification dans le menu de gauche

![error-profil](https://user-images.githubusercontent.com/1496191/57012884-e809b800-6c08-11e9-93c6-806a709c5c37.gif)

>> DONE

2019-05-01 13:01 UTC, Sylvaner commented
![Capture d’écran 2019-05-01 à 14 59 47](https://user-images.githubusercontent.com/957104/57018010-eb5d6d80-6c21-11e9-9616-95d603172745.png)

Euh... c'est pas très beau dans ma hiérarchie de pièces...

2019-05-02 10:08 UTC, slobberbone commented on src/Helpers/FileSystemHelper.php
> +                    'jquery.ui/jquery-ui-bootstrap/jquery-ui' => 'assets/css/vendors/jquery-ui-bootstrap/jquery-ui.css'
https://www.npmjs.com/package/jquery-ui
On utilise npm normalement et il est dispo ...

2019-05-02 12:10 UTC, cyrilphoenix71 commented on src/Helpers/FileSystemHelper.php
> +                    'jquery.ui/jquery-ui-bootstrap/jquery-ui' => 'assets/css/vendors/jquery-ui-bootstrap/jquery-ui.css'
>> ISSUE #1064

2019-05-02 19:19 UTC, Gis70 approved these changes

2019-05-02 19:25 UTC, Gis70 commented
> lorsqu'on modifie sa photo de profile, il faut regarder 2 fois la page avant de voir apparaître le modification dans le menu de gauche
> 
> ![error-profil](https://user-images.githubusercontent.com/1496191/57012884-e809b800-6c08-11e9-93c6-806a709c5c37.gif)
> 
> > > DONE

J'ai dû faire un ctrl f5 pr avoir l'avatar sinon  : 
![image](https://user-images.githubusercontent.com/16589132/57101108-ce5b9400-6d20-11e9-8547-ef8c654ac70a.png)

2019-05-03 06:20 UTC, psycofdj approved these changes

2019-05-03 06:20 UTC, psycofdj commented
beau boulot @cyrilphoenix71 !

2019-05-03 11:10 UTC, Gis70 commented
ok pr avatar

2019-05-03 14:23 UTC, merged