Fix bug des noms des dépots
NextDom/nextdom-core pull request #1166
Opened 2019-07-14 04:29 UTC by Sylvaner

Permet d'installer des applications depuis le market nextdom

2019-07-14 05:15 UTC, ColonelMoutarde approved these changes

2019-07-15 08:04 UTC, byackee commented
![image](https://user-images.githubusercontent.com/4707496/61202396-b2447d80-a6e7-11e9-8b87-2dc5738a74f1.png)

Toujours ce pb, j'ai peut être fais une fausse manip mais après l'install d'un plugin il n'y a rien dans le repertoire plugins

2019-07-15 08:07 UTC, byackee requested changes
Voir commmentaire de la PR et sur le market jeedom j'ai ca
![image](https://user-images.githubusercontent.com/4707496/61203132-d2753c00-a6e9-11e9-8eaa-49c81af73e60.png)

2019-07-17 06:17 UTC, Sylvaner commented
@byackee C'était justement le problème.
J'ai push un correctif.

2019-07-18 14:23 UTC, byackee approved these changes
tout est ok !!

2019-07-18 15:01 UTC, slobberbone approved these changes
Testé : ajout/suppression plugin depuis Jeedom Market
Testé : ajout/suppression plugin depuis NextDom Market

Tout est ok

2019-07-18 15:01 UTC, merged