Nettoyage
NextDom/nextdom-core pull request #1256
Opened 2019-07-30 19:33 UTC by Sylvaner

Suppression des variables $object pour une éventuelle compatibilité avec les versions supérieurs de php
Commentaires et amélioration de la lisibilité de certaines classes.

A tester : Le fonctionnement général.

2019-07-30 19:55 UTC, ColonelMoutarde approved these changes

2019-07-30 19:57 UTC, ColonelMoutarde commented
Salut, le mot clés object qui est un mot réservé pas $object.  Mais bon c’est pas plus mal de changer, c’est plus clair.

2019-08-10 13:12 UTC, Gis70 requested changes
J'ai plein d'erreurs sur tous mes plugins 
![image](https://user-images.githubusercontent.com/16589132/62822258-40920f00-bb81-11e9-8347-c2a647daca6b.png)

2019-08-11 17:16 UTC, Sylvaner commented
C'est corrigé (j'ai force push pour éviter un commit)

2019-08-12 19:15 UTC, Gis70 approved these changes

2019-08-13 05:38 UTC, merged