Remplacement des graphs highstock par chartJS
NextDom/nextdom-core pull request #1263
Opened 2019-07-31 13:08 UTC by byackee

tester tous les graphs dans:
- design
- commande
- page historiques

2019-08-08 22:51 UTC, Gis70 requested changes
Par défaut, un graphique sur le dash charge tous les points existant ce qui est très long, on peut réduite à 1 mois ?

Comment fait on un zoom ?

2019-09-07 13:14 UTC, byackee commented
Salut @Gis70 normalement ça doit être 7 jours dans le dash, je vais regarder ce qui se passe.

Pour faire un zoom c'est avec la molette nde la souris lorsque le pointeur est sur le graphique

2019-09-18 17:23 UTC, Esso1-jeedom commented
alors ca marche chez moi par contre  j'ai du charger des vendor qui manquaient
vendor/node_modules/chartjs-plugin-zoom/dist/chartjs-plugin-zoom.min.js:
 vendor/node_modules/hammerjs/hammer.min.js:
vendor/node_modules/chart.js/dist/Chart.bundle.min.js: 
vendor/node_modules/jstree/dist/jstree.js:
vendor/node_modules/jwerty/jwerty.js:

apres ca, ca marche trés bien  , zoom affichage ligne air ...

2019-09-18 17:26 UTC, Esso1-jeedom approved these changes

2019-09-24 20:46 UTC, slobberbone commented
@byackee si tu veux qu'on l'intègre, si on l'intègre @Sylvaner  ? faudra que tu gères le conflit pour eviter des boulettes !

2020-03-19 08:29 UTC, closed without merging