Possibilité de stopper les scénarios et voir leur état
NextDom/nextdom-core pull request #1308
Opened 2019-08-26 05:59 UTC by Sylvaner

Gestion des scénarios avec les états dans la vue mobile : 

![Capture d’écran 2019-08-26 à 07 59 03](https://user-images.githubusercontent.com/957104/63668450-779a2e80-c7d7-11e9-8cb1-c0e1374d8bf7.jpg)

2019-08-27 14:05 UTC, cyrilphoenix71 requested changes
Affichage et lancement 1er scenario OK
J'ai ajouté l'état error des scenario
Mais le lancement des 2e, 3e etc scenario créer une error 500
![image](https://user-images.githubusercontent.com/18350629/63778025-67bc4080-c8e4-11e9-9dbd-ad12c27defc6.png)

2019-09-02 05:42 UTC, Sylvaner commented
Pas de lien, c'est le user.function.php qui est testé mais je n'arrive pas à reproduire. Cependant tu dois avoir beaucoup d'autres problèmes :)

2019-09-05 14:33 UTC, cyrilphoenix71 commented
ok alors je valide car ca fonctionne et apres nettoyage de user.fonction on verra

2019-09-05 14:33 UTC, cyrilphoenix71 approved these changes

2019-09-08 09:51 UTC, merged