Feature/pace loading
NextDom/nextdom-core pull request #1412
Opened 2019-10-13 19:28 UTC by CyrilCharlier

Changement du loader : Passage au Pace d'AdminLte

Ajout du JS du plugin
Ajout du SCSS
Modification de la page de Customisation
Suppression de la référence de cette préférence dans la Back (Fichier Ini) et Front (JS)

2019-10-13 20:50 UTC, ColonelMoutarde requested changes
Salut,
Il faut que tu utilise les fonctionnalité de sass stp. Là c'est du code css.
Peux-tu refactorer stp

2019-10-13 21:07 UTC, CyrilCharlier commented
euh oui mais là il faudrait un coup de main car je n'y connais rien

2019-10-14 05:17 UTC, CyrilCharlier commented
@ColonelMoutarde c'est du SCSS ou du sass ?
Car après quelques recherches ce serait plutôt du SCSS ?

Je ne voudrais pas partir sur un mauvais refactoring. 

Merci et bonne journée

2019-10-14 06:17 UTC, ColonelMoutarde commented
Salut, Sass est le nom du protocole. On peut faire du sass et du scss. Nous utilisons scss.

2019-10-14 06:19 UTC, CyrilCharlier commented
Salut, comme tu vois je ne connais vraiment pas :D Merci pour la précision

2019-10-14 20:46 UTC, CyrilCharlier commented
Voilà les différentes remarques ont été prises en compte. Si vous en avez d'autres, n'hésitez pas à me le dire

2019-10-15 18:58 UTC, ColonelMoutarde approved these changes

2019-10-18 06:35 UTC, Sylvaner approved these changes

2019-10-18 12:54 UTC, merged