fix issue 1423
NextDom/nextdom-core pull request #1424
Opened 2019-10-18 12:58 UTC by cyrilphoenix71

Fix : 
- fix issue #1423

To test :
- test postinst in mode -D or not

2019-10-18 14:59 UTC, ColonelMoutarde commented
Salut,
Serait-il possible de mettre les clés de traduction pour que nous les traduisions ensuite ? Plutôt que des mot en français ?

2019-10-22 08:33 UTC, ColonelMoutarde approved these changes

2019-10-23 10:14 UTC, slobberbone commented
Concretement, je ne sais pas ce que ca fait, ni comment tester ...

2019-10-25 17:04 UTC, Gis70 requested changes
dans le postinst on appelle :
` -D            : copy values of dist/dev.config.ini.dist in default.config.ini`

et non default.config.ini.dev c'est pour ça que ça ne marche pas

2019-10-27 09:57 UTC, Gis70 approved these changes
J'approuve même si ça fonctionne pas pour le -D mais ce n'est pas l'objet de la PR :)

2019-10-27 09:57 UTC, merged