Correction eqAnalyse
NextDom/nextdom-core pull request #1435
Opened 2019-10-22 15:00 UTC by Sylvaner

https://github.com/NextDom/nextdom-core/issues/1377

2019-10-22 19:50 UTC, Gis70 requested changes
c'est corrigé à 50% :
https://cdn.discordapp.com/attachments/536500991923585091/636289863557054484/unknown.png

dans la page alerte définie c'est toujours pas bon, par contre c'est OK dans Actions définies

2019-10-22 21:29 UTC, Gis70 approved these changes

2019-10-22 21:29 UTC, Gis70 commented
ok ça roule

2019-10-23 09:45 UTC, slobberbone approved these changes

2019-10-23 09:45 UTC, merged