Intégration de la version mobile
NextDom/nextdom-core pull request #1467
Opened 2019-10-30 17:19 UTC by Sylvaner

Suppression du menu si la version mobile n'est pas installée
Ligne de commande pour l'installer par apt si l'installation de nextdom s'est fait comme ça

A tester : La sélection de la commande d'installation au clic sur différents navigateur, internet explorer n'a pas pu être testé.

2019-10-31 16:43 UTC, Gis70 approved these changes
OK, par contre pour valider l'instal via apt il faut un deb, donc c'est à moitié validé :)

2019-10-31 21:42 UTC, Sylvaner commented
Ou git clone

2019-11-02 13:29 UTC, vinceg77 requested changes
testé sur mon Xiaomi Mi8 android avec :
- Chrome mobile
- Opéra mobile
- Firefox mobile
- Navigateur Mi
Tout fonctionne c'est à dire que ca copie bien la commande qui s'affiche en fonction du type d'install.

Par contre je reste très dubitatif sur la fonctionnalité....

Approuvé à 1/3 donc !

2019-11-02 20:07 UTC, vinceg77 approved these changes
Après concertation auprès de ma hiérarchie :) (@GiDom) je valide cette PR parce qu'elle fonctionne (mais toujours à 1/3)
Mais je pense toujours pas qu'il faille l'intégrer dans une prochaine release de Nextdom tant cette fonction ne me parait pas au standard ! Le prenez pas mal.

2019-11-04 04:42 UTC, merged