Fix issue 1466 : Variable cleaning
NextDom/nextdom-core pull request #1476
Opened 2019-11-04 14:07 UTC by cyrilphoenix71

fix #1466

To test : 
- postint
- check all is good
- try change theme icon in page admin/profils, tab theme
- check flag display in market plugin modale

2019-11-04 20:33 UTC, vinceg77 approved these changes
No problem sur la PR en elle même.

Par contre il y a un petit bug d'image dans les badges des plugins sur le market Nextdom (apparemment non lié à cet évol, il existe depuis toujours) :
![image](https://user-images.githubusercontent.com/51484329/68155789-b58b9f80-ff4a-11e9-931a-142a9dc24f9b.png)

2019-11-05 07:49 UTC, Sylvaner commented
![Capture d’écran 2019-11-05 à 08 48 55](https://user-images.githubusercontent.com/957104/68188310-219cf080-ffa9-11e9-89a4-3065567b3b87.jpg)

2019-11-05 07:50 UTC, Sylvaner requested changes
![Capture d’écran 2019-11-05 à 08 48 55](https://user-images.githubusercontent.com/957104/68188387-4beeae00-ffa9-11e9-8462-4039264c7231.jpg)

2019-11-05 08:35 UTC, vinceg77 commented
Étrange, moi je n'ai pas ca.
![image](https://user-images.githubusercontent.com/51484329/68191311-96732900-ffaf-11e9-87ef-8ca439277728.png)

2019-11-06 21:00 UTC, ColonelMoutarde approved these changes

2019-11-08 14:07 UTC, closed without merging