add security score in firstUse, Profil & user pages
NextDom/nextdom-core pull request #1579
Opened 2019-12-05 10:24 UTC by cyrilphoenix71

fix #1572

Pour tester :
- faire un postinstall
- verifier que l'assistance visuelle de niveau de sécurité mot de passe fonctionne en step2 et que le firstuse se deroule bien jusqu'à la fin
- tester le changement de mot de passe en page PROFIL en verifiant que l'assistance visuelle de niveau de sécurité mot de passe fonctionne
- tester le changement de mot de passe en page USERS en verifiant que l'assistance visuelle de niveau de sécurité mot de passe fonctionne

2019-12-05 11:07 UTC, dcjona approved these changes

2019-12-05 19:51 UTC, iWils requested changes
Suite à des tests différents tests effectués avec Firefox et Chrome, je relève un problème aléatoire lors du changement de mot de passe via la page USERS depuis l'extérieur.

Avec une adresse locale, il n'y a pas de soucis, mais dès lors que l'on passe par une adresse en nextdev.xxx.fr, l'encart de mot de passe ne s'ouvre pas et on peut relever l'erreur suivante:
![image](https://user-images.githubusercontent.com/56263502/70267693-3be00f00-179f-11ea-8da6-c39fa8846ac6.png)

2019-12-06 09:40 UTC, TekiStone requested changes
Suite à différent tests, lorsque j'arrives sur la page PROFIL un mot de passe semble renseigné par défaut et le score du mot de passe affiche "Moyenne", après saisi d'un nouveau mot de passe fort, l'indicateur indique "Très Forte".

Affichage de la page, pas de modification :
![image](https://user-images.githubusercontent.com/35001669/70312691-7041e280-1814-11ea-8247-5c8f6178da8c.png)

Saisie d'un nouveau mot de passe :
![image](https://user-images.githubusercontent.com/35001669/70312731-8059c200-1814-11ea-9f91-48bbde907453.png)

Après sauvegarde du mot de passe : 
![image](https://user-images.githubusercontent.com/35001669/70312746-88b1fd00-1814-11ea-90e3-24e5cd049775.png)

Ce n'est pas une ano en soit mais c'est perturbant pour l'utilisateur et ça laisse penser que le mot de passe est véhiculé en clair depuis le back.

2019-12-06 11:48 UTC, vinceg77 requested changes
Je rencontre les memes pbs que ceux trouvés par @iWils et @TekiStone

2019-12-06 14:39 UTC, vinceg77 approved these changes
Corrigé !
Tout nickel chez moi !

2019-12-06 23:25 UTC, iWils approved these changes
Suite à l'update tout est ok.

Validé

2019-12-07 11:14 UTC, TekiStone approved these changes
Ok pour moi, tout est corrigé.

2019-12-07 11:17 UTC, TekiStone reviewed
Deux petites remarques visuelles : 
Il y a un delta entre le changement de mdp de la page user et profil : 
Page User : 
Y'a une mini popup de confirmation de sauvegarde
Page profil : 
A la sauvegarde on recharge la page et on a pas de "confirmation" vraiment

Et le fait que sur la page profil on arrive avec un mdp déjà renseigné est perturbant, pas possible de le laisser à vide ?

2019-12-07 11:17 UTC, merged