Fix et optimisation CSS
NextDom/nextdom-core pull request #1590
Opened 2019-12-10 22:02 UTC by Sylvaner

https://github.com/NextDom/nextdom-core/issues/1589

Optimisation pour adminlte.

Tester le dashboard et surtout le modal de choix d'un icône

2019-12-12 19:31 UTC, vinceg77 commented
L'icone a tester est celui qui apparaît dans la fenêtre popup quand on veut changer l'icone d'une piece ou de tout autre objet

2019-12-13 23:19 UTC, iWils requested changes
Lors du test j'ai perdu toutes les icônes de mes pièces et dans la liste il n'y a plus rien jusqu'à 'font-awesome-5-regular'

![image](https://user-images.githubusercontent.com/56263502/70838153-328e1c80-1e07-11ea-8e8b-93b1529e36ed.png)

![image](https://user-images.githubusercontent.com/56263502/70838160-3a4dc100-1e07-11ea-8b5b-3093a7203fe1.png)

![image](https://user-images.githubusercontent.com/56263502/70838167-420d6580-1e07-11ea-9b4b-9c5c6c102abe.png)

2019-12-14 09:31 UTC, slobberbone commented
@iWils tu as bien vider les différents cache ? gen_assets ?

2019-12-14 09:43 UTC, iWils reviewed
Bonjour @slobberbone 
- CTRL + F5 fait
- gen_asset fait
- postinst fait
et toujours le même souci
de plus j'ai désactiver le cache sur le navigateur.

2019-12-14 11:38 UTC, vinceg77 requested changes
Divers problèmes pour moi également : 

Dashboard
------------
Fonctionnent globalement mais je suis tombé a un moment sur des tuiles repliées : 
![2019-12-14 12_22_29-Window](https://user-images.githubusercontent.com/51484329/70848185-f8a43100-1e6d-11ea-89fb-a2b350a24506.png)
Sans toutefois parvenir à reproduire le problème

Icônes
---------

Sur la page objet, j'obtiens bien une liste d’icônes mais tous ne s'affichent pas : 
![Icones](https://user-images.githubusercontent.com/51484329/70848203-3e60f980-1e6e-11ea-8dee-2fa040dfaeb8.png)
![Icones2](https://user-images.githubusercontent.com/51484329/70848204-3f922680-1e6e-11ea-891a-d38c5affc311.png)
Les catégories suivantes n'affichent pas d'icône mais un texte de remplacement : ANIMAL / DIVERS / FASHION / LOISIR / MAISON / METEO / NATURE / NEXTDOM / NEXTDOM2 / NETXDOMAPP / NOURRITURE / PERSONNE / SECURITE / TECHNO / TRANSPORT

Par contre les catégories suivantes affichent bien leurs icones : 
FONT-AWESOME-5-REGULAR
FONT-AWESOME-5-SOLID
FONT-AWESOME-5-BRANDS

Ces problemes d'affichage correspondent aux erreurs trouvées par Travis : 
```[{'level': 'SEVERE', 'message': 'http://127.0.0.1:8765/icon/animal/style.css - Failed to load resource: the server responded with a status of 404 (Not Found)', 'source': 'network', 'timestamp': 1576276608830}, {'level': 'SEVERE', 'message': 'http://127.0.0.1:8765/icon/divers/style.css - Failed to load resource: the server responded with a status of 404 (Not Found)',```

2019-12-18 19:53 UTC, Gis70 requested changes
Hello, chez moi il me manque des icônes dans le plugin monitoring et dans un widget 
![image](https://user-images.githubusercontent.com/16589132/71118420-66d35580-21d8-11ea-84d4-5fb08e00ad76.png)
![image](https://user-images.githubusercontent.com/16589132/71118441-79e62580-21d8-11ea-9ddd-566d9c4c5e5a.png)

via plugin widget :
![image](https://user-images.githubusercontent.com/16589132/71118475-87031480-21d8-11ea-9f7f-37d629f4a7ec.png)

![image](https://user-images.githubusercontent.com/16589132/71118495-8f5b4f80-21d8-11ea-8f0b-cf4be174eb03.png)

2019-12-18 21:54 UTC, iWils requested changes
Bonsoir,

Je confirme les dires de @Gis70, je rencontres des soucis d'affichage d'icône sur le pluging Monitoring, GoogleCast et Xiaomi:
- Monitoring
![image](https://user-images.githubusercontent.com/56263502/71126142-b28dfb00-21e8-11ea-9862-16094ad3661b.png)

- GoogleCast:
![image](https://user-images.githubusercontent.com/56263502/71126289-ff71d180-21e8-11ea-9f44-7175212a26d5.png)

- Xiaom
![image](https://user-images.githubusercontent.com/56263502/71126387-2cbe7f80-21e9-11ea-80ad-14ecb5fb849f.png)

2019-12-19 14:39 UTC, Sylvaner commented
C'est corrigé, c'était l'ordre des icones qui autorise des choses qui ne devraient pas fonctionner

2019-12-19 21:40 UTC, iWils commented
Bonsoir,
Après un nouveau test je ne rencontre plus de soucis avec le plugin Monitoring.
![image](https://user-images.githubusercontent.com/56263502/71211645-d9633480-22af-11ea-99a8-c3cce265e8a6.png)

En revanche j'ai toujours un soucis avec l'icône de mon widget GoogleCast 
- Mute Off
![image](https://user-images.githubusercontent.com/56263502/71211751-13343b00-22b0-11ea-8fc8-5f4921c5417e.png)
- Mute On
![image](https://user-images.githubusercontent.com/56263502/71211777-1fb89380-22b0-11ea-81ff-a6dc336d4164.png)

Mais en réalité le problème est plus général, car l'icône utilisé est btnCircle
![image](https://user-images.githubusercontent.com/56263502/71211888-64442f00-22b0-11ea-8f65-9059c17c326c.png)

Cela a été observé car d'autre Pluging utilisant 'btnCircle' on le même soucis

2019-12-23 21:33 UTC, vinceg77 approved these changes
Tout bon pour moi !

2019-12-24 08:43 UTC, merged