Manage not existing cache file
NextDom/nextdom-core pull request #1592
Opened 2019-12-11 10:27 UTC by slobberbone

Fix https://github.com/NextDom/nextdom-core/issues/1591

2019-12-11 15:24 UTC, vinceg77 commented
@TesteursFous  : vérifier qu'il n'y ait plus d'erreur liée au cache dans la fenêtre de log de restauration d'un backup

2019-12-11 15:37 UTC, vinceg77 approved these changes
Tout bon chez moi !

> [ Restore Backup Process ]

*************** starting restore procedure at 2019-12-11 16:36:41 ***************
...file used for restoration: /var/lib/nextdom/backup/backup-MaisonChelles-0.6.0-2019-12-11-07-24-02.tar.gz
OK
stopping Nextdom system......  OK
extracting backup archive......  OK
restoring plugins......  OK
restoring mysql database......  OK
importing Jeedom configuration......  OK
restoring custom data...
... ...Restoring folder: config
OK
...Restoring folder :3d
OK
...Restoring folder :custom
OK
...Restoring folder :object
OK
...Restoring folder :plan
OK
...Restoring folder :view
OK
OK
migrating data...... ...Migration/Update process from --> 0.6.0
...Migration/Update process to --> 0.6.0
...Replace jeedom in database
OK
starting nextdom system......  OK
updating system configuration......  OK
checking system consistency......  OK
init values......  OK
clearing cache......  OK
restoring cache......  OK
*************** end of restore procedure at 2019-12-11 16:36:59 ***************
*************** elapsed time 18 ***************
*************** Closing with success ***************
[ / Restore Backup Process ]

>

2019-12-12 22:54 UTC, iWils requested changes
Restauration OK.
Quelques erreurs recensés mais qui n'ont rien a voir directement avec la PR (erreur dans l'issue #1608)

PR Validé

2019-12-13 00:15 UTC, iWils approved these changes

2019-12-13 00:22 UTC, merged