fix #1547
NextDom/nextdom-core pull request #1593
Opened 2019-12-11 10:41 UTC by byackee

tester influxDB et surtout l'erreur "partial write"

2019-12-11 12:14 UTC, dcjona requested changes
impossible de changer sur cette pr le sous type d'un équipement... 

![pr1547](https://user-images.githubusercontent.com/34706426/70620616-0791a600-1c18-11ea-8d4c-5146aabf0976.png)

alors que sur la 0.6.0

![0 6 0](https://user-images.githubusercontent.com/34706426/70620664-25f7a180-1c18-11ea-8d27-f805dc56f833.png)

2019-12-11 12:16 UTC, dcjona requested changes
J'obtiens ce type d'erreur 

2019-12-11 00:00:00 | plugin | Erreur sur plugin::cron() : HTTP Code 400 {"error":"partial write: field type conflict: input field \"value\" on measurement \"state\" is type float, already exists as type integer dropped=1"} |  
-- | -- | -- | --
2019-12-11 00:00:00 | virtual | Erreur exécution de la commande [Virtuels][MotionEye][On_Cam_salon] : HTTP Code 400 {"error":"partial write: field type conflict: input field \"value\" on measurement \"state\" is type float, already exists as type integer dropped=1"} |  
2019-12-11 00:00:00 | jeeEvent | HTTP Code 400 {"error":"partial write: field type conflict: input field \"value\" on measurement \"state\" is type float, already exists as type integer dropped=1"}

lié a influxdb ou pas ?

2019-12-13 19:41 UTC, dcjona requested changes
Je n'ai plus d'erreur lié à influxDB il me semble par contre :

2019-12-13 00:00:00 | espeasy | Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement |  
-- | -- | -- | --
2019-12-13 00:00:00 | maxcube | Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement |  
2019-12-13 00:00:00 | rflink | Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement |  
2019-12-13 00:00:00 | rflink | Erreur sur la fonction deamon_start du plugin : Le port : n'existe pas |  
2019-12-13 00:00:00 | squeezeboxcontrol | Attention je pense qu'il y a un soucis avec le démon que j'ai relancé plus de 3 fois consecutivement

2019-12-30 16:33 UTC, Adrianos712 commented
Hello,

plus d'erreur influxDB de mon coté, par contre ça ne stock plus les valeurs à 0 (par exemple un interrupteur binaire).

J'imagine que ça vient de ça : 
`                 && (!empty($valueToSend))) {`

Il faudrait vérifier que c'est pas NULL mais qu'on puisse envoyer des 0 vers influxDB quand même.

2019-12-30 16:42 UTC, Adrianos712 requested changes
Hello,

plus d'erreur influxDB de mon coté, par contre ça ne stock plus les valeurs à 0 (par exemple un interrupteur binaire).

J'imagine que ça vient de ça :
`&& (!empty($valueToSend))) {`

Il faudrait vérifier que c'est pas NULL mais qu'on puisse envoyer des 0 vers influxDB quand même.

2020-01-07 22:43 UTC, slobberbone commented
@Adrianos712 j'ai pris en compte ta remarque. Tu peux retester ?

2020-01-13 13:57 UTC, Adrianos712 approved these changes
C'est bon pour moi, merci ! :)

2020-01-15 16:04 UTC, dcjona approved these changes
ok il me reste un soucis qui n'est pas en lien direct avec le fix, pour celui ci de mon coté c'est ok aussi lors des tests

2020-01-16 15:13 UTC, merged