Review installation script
NextDom/nextdom-core pull request #1614
Opened 2019-12-20 23:12 UTC by slobberbone

Review postinst file

Review installation script

Add preinst file

preinst

postinst

add preinst

avancement

test

2019-12-21 12:11 UTC, Esso1-jeedom commented
![image](https://user-images.githubusercontent.com/40739563/71307769-64007c80-23f3-11ea-907d-98e0e5324ea0.png)

2019-12-21 13:09 UTC, Esso1-jeedom commented
install git classique 
ou j'ai fait un changement de branche
install_git.sh
var/www/html/install#

2019-12-22 22:50 UTC, edgd1er commented
Large remaniement ;) je n ai pas testé le code, juste lu. 
SysVInit à été remplacé par SystemD, pourquoi ne pas utiliser systemctl ? 
qq remarques pr docker principalement :
Est il possible de detecter l etat docker pour bypasser les services stop/start, inutiles ds docker ?
le conteneur mysql aura deja son user, mdp et db crees. Est il possible de bypasser les étapes de création si le mdp root mysql est absent/vide ?

2019-12-28 17:16 UTC, edgd1er commented
pour les addlog, en mode docker aucun dossier n'est préexistant, du coup addLogInfo plante dès le début car /var/log/nextdom n'existe pas, il faudrait le créer et/ou detecter son absence.

2020-01-06 22:24 UTC, slobberbone commented
@edgd1er oui pour le moment c'était voulu de ne proposer "que" la même chose qu'avant pour permettre de ne pas constater de régressions.
Pour tes modifications, je veux bien les prendre mais le soucis, c'est que tu as archivé des modifications en mm temps que des tabulations supprimées ou rajoutées ... du coup c pas très lisible

2020-01-07 22:26 UTC, slobberbone commented
@edgd1er j'ai gardé ce que tu avais fais, mais virer les options ${docker} en direct mais j'ai rajouté dans le config.sh
Là tout semble ok

2020-01-07 22:31 UTC, slobberbone commented
@edgd1er Pour tes améliorations, je te propose de voir ça dans un second temps

2020-01-08 07:14 UTC, Esso1-jeedom commented
![image](https://user-images.githubusercontent.com/40739563/71957777-edcf8880-31ee-11ea-8a8a-725adb574795.png)

2020-01-08 07:34 UTC, Esso1-jeedom commented
![image](https://user-images.githubusercontent.com/40739563/71958896-b6aea680-31f1-11ea-9eb5-2b4e7bf1eb2d.png)

2020-01-08 21:31 UTC, slobberbone reviewed
c bizare @Esso1-jeedom ca donne l'impression qu'il te manque des fichiers ...

2020-01-08 22:18 UTC, Gis70 reviewed
![image](https://user-images.githubusercontent.com/16589132/72020871-09797400-326d-11ea-9786-970cb812fd2a.png)

dossier /html renommé

Peux tu écrire la procédure pour une installation depuis github

2020-01-09 23:16 UTC, vinceg77 commented
@testeurFou : tester 
1/ sur différentes plateformes
2/ Depuis une install vierge
3/ Depuis un update (de 0.5.4 à 0.6.0 par exemple)

2020-01-10 07:51 UTC, Esso1-jeedom commented
alors c toujours pareille pour moi . aprés une install Git classique . je passe sur la branche ,
je lance le install git.. et rien ne marche .

2020-01-10 09:47 UTC, Esso1-jeedom commented
bon aprés modif  du config.sh 
ROOT_DIRECTORY="/var/www/nextdomdev"

![image](https://user-images.githubusercontent.com/40739563/72143231-9d932a80-3396-11ea-8c82-61040df40e53.png)

ca marche pour moi

2020-01-10 09:48 UTC, Esso1-jeedom approved these changes

2020-01-10 23:31 UTC, Gis70 requested changes
- Partant d'une install sans nextdom, jai dû lancer gen_composer manuellement avec de lancer l'install git, pourquoi n'est il pas lancé ?

- De plus il y a un soucis de gen_assets aussi ? 

![image](https://user-images.githubusercontent.com/16589132/72193463-e0421a80-3409-11ea-8af3-584a49fc604e.png)

- Pb d'affichage du mot de passe de la db ?

![image](https://user-images.githubusercontent.com/16589132/72193505-2303f280-340a-11ea-8116-d6f063a249a5.png)

2020-01-11 06:31 UTC, edgd1er commented
Plusieurs remarques:

* pourquoi remplacer les tests []  (compatible posix) par des [[ ]] ( non compatibles posix) alors que ce n'est pas nécéssaire.
* pourquoi mettre la configuration mysql a deux endroits maintenant config.sh et mysql/secret ? Pour docker, la conf est a 4 endroits maintenant: docker-compose.yml, mysql/secret, config.sh, common.config.php. quelle est l'utilité de ce mysql secret ? il n'est pas spécifique docker ( besoin de swarm)
* aucune fonction ne modifie "result", de ce fait le log indique a chaque fois que c'est ok
* les booleen avec bash sont "bizarres", [[ ! $VARIABLE ]] sera vrai a chaque fois

```
$ PRODUCTION=true
$ [[ $PRODUCTION ]] && echo toto
toto
$ PRODUCTION=false
$ [[ $PRODUCTION ]] && echo toto
toto
$ [[ $PRODUCTION == false ]] && echo toto
toto
$ PRODUCTION=true
$ [[ $PRODUCTION == false ]] && echo toto
$ 
```

2020-01-12 14:28 UTC, Astral0 commented
OK avec toi pour les [[ ]] on peut les changer en [ ].

Pour mysql/secret je pense qu'il ne sert pas.

De manière générale, je ne comprends pas la logique de faire "source toto.sh" et d'appeler les méthodes une à une.  Vu qu'on source 3 ou 4 fichiers, on se met en risque (mélange de fonctions et variables).

Perso je pense qu'on peut faire beaucoup plus simple : 
- un install/postinst qui est lancé par tous les utilisateurs d'une version dev (git clone + ./install/postinst). Il est lancé aussi par le paquet deb.
- le fichier postinst commence par déterminer si c'est une vdev ou apt, voir s'il est dans Docker (si c'est possible de le déterminer, ca sera plus simple).
- si vdev, alors postinst lance presinst, fait ses manips, et continue ensuite la procédure postinst
- si Docker, alors il lance *jesaispasquoi*, peut être un "preinst_docker" qui lance (ou pas) preinst, puis ensuite, postinst continue.

Je trouve cette multiplication des fichiers bash contre-productive, et avoir plusieurs points d'entrée c'est encore pire.. C'est clair qu'on va perdre les utilisateurs.
Dans tous les cas, on devrait juste demander à l'utlisateur de lancer "./install/postinst".

Je rappelle que c'est comme ca qu'est construit actuellement le fichier postinst, et qu'on avait dit qu'on éclatait juste ce fichier pour sortir ce qui n'est à faire que pour la vdev (et docker). On n'a jamais parlé du fait que l'utilisateur devait lancer un script ou un autre selon son contexte.

AA

2020-01-12 14:59 UTC, Astral0 commented
Cette partie du postinst.sh n'a rien à faire là (elle n'était affichée que dans le cas d'une vdev) :

```
cat - <<EOS
  Installation dir  : ${ROOT_DIRECTORY}
  Database host     : ${MYSQL_HOSTNAME}
  Database port     : ${MYSQL_PORT}
  Database name     : ${MYSQL_NEXTDOM_DB}
  Database user     : ${MYSQL_NEXTDOM_USER}
  Database password : ${MYSQL_NEXTDOM_PASSWD}
  > A self-signed SSL Certificate created in /etc/nextdom/ssl/
  > Please feel free to use another Certificate
  >>>>> COMPLETED <<<<<
EOS
```

2020-01-12 18:40 UTC, edgd1er commented
@Astral0 respires un grand coup ça ira mieux :)

L'idée initiale de @slobberbone  est de découper l'installation et la configuration en étapes. Ces étapes sont réparties dans deux fichiers selon le type d'installation ( git dev, deb, docker ). 

par exemple, une installation deb ne va avoir besoin que du postinst, une installation git et dev va avoir besoin du pre et du post. Voila qui devrait te rassurer quand a la multiplication des bash. @slobberbone a juste exporter la configuration et les fonctions communes dans deux fichiers bien nommés: config.sh et utils.sh. Ces deux fichiers sont appelés par les scripts les nécéssitant, donc c'est transparent pour l'utilisateur. Et puis ne pas prendre l'utilisateur pour un idiot mais lui indiquer comment faire dans un README fait partie des bonnes pratiques aussi. On peut le guider ;)

Le découpage actuel pré/post inst est adapté pour un installation de dev ce que je ne remets pas en cause. J'ai adapté le install_docker.sh via des sources pour ne prendre que les étapes utiles et nécéssaires à l'installation docker. Justement, je prends à mon compte la complexité pour changer le moins possible le pre et postinst, afin que les deux scripts restent utilisables tel que @slobberbone les a définit. C'est pour ça que les opérations des étapes ne doivent concerner qu'un sujet ( pas comme l'étape 6 du post qui mélange des étapes de l'installation modification du temp et des étapes de l'execution, modification des variables et injection du schema dans la bdd ). 

Je me repete, le but est bien de conserver le fonctionnement actuel:
* deb + postinst.sh
* git clone + pre-inst + postinst
* dockerfile + qq fct pre-inst + qq fct postinst

@slobberbone si j'ai mal compris tes intentions dans cette PR, n'hésites pas à me corriger.

pour info, dans mon dockerfile j'utilise la version buster ( balenalib/amd64-debian:buster-run), si vous jeter un oeil c'est la: https://github.com/NextDom/nextdom-docker.git dans la branche refactorPostInst. La construction se passe en trois étapes
* build d'une image de base
* build d'une image de dev depuis l'image de base et generation des fichiers ( css, js, themes, ....)
* build d'une image de prod depuis l'image de base avec copie des fichers générés. publication de cette image.
L'image produite est loin d'être legere ( 900Mb) mais la version une seule etape etait pire (1.3Gb).

2020-01-17 20:38 UTC, slobberbone commented
@edgd1er peux-tu te connecter à Discord stp Je revois ton install_docker pour le mettre au propre

2020-01-17 23:49 UTC, Gis70 approved these changes
Fresh install debian 10, install_git OK merci

2020-01-20 23:22 UTC, Gis70 requested changes
Il y a un pb de restitution du mdp DB : 
![image](https://user-images.githubusercontent.com/16589132/72763449-1cccfd80-3be4-11ea-9375-84a92bb34847.png)

2020-01-21 00:31 UTC, vinceg77 commented
Installe ok mais pb de mot de passe (cf ci dessus)

2020-01-21 00:34 UTC, vinceg77 requested changes
Installe ok mais pb de mot de passe sur la page OS/DB (cf ci dessus)

2020-01-23 12:10 UTC, Gis70 approved these changes

2020-01-26 19:55 UTC, Esso1-jeedom commented
j'ai une question normale qu'un rep html soir recréé sous /var/www/html/html
![image](https://user-images.githubusercontent.com/40739563/73140892-3061e380-407e-11ea-9619-94171ce85697.png)
sinon c parfait

2020-01-27 15:15 UTC, Esso1-jeedom commented
debian 10 
armbian 10
Sources dans /var/www/nextdomdev 

Installation par Git + paquets debian : nextdom-common  + changement de branche.

Installation par Git + paquets debian : nextdom-common  
git clone https://github.com/NextDom/nextdom-core.git -b feature/RefactorPostinst . 
![image](https://user-images.githubusercontent.com/40739563/73186578-432cf480-4120-11ea-8c8e-e736d0c18340.png)

2020-01-29 18:48 UTC, Esso1-jeedom commented
bon tjrs la merde sur fresh install.
manque tjrs le rep 
/usr/share/nextdom 
du coup ca marche pas 
en créer le rep 
j'ai le truc qu'on a pas le droit .
![image](https://user-images.githubusercontent.com/40739563/73385195-06523080-42cd-11ea-9b34-cd72118f825d.png)
quand on sup le nextdom_common
![image](https://user-images.githubusercontent.com/40739563/73386548-4f0ae900-42cf-11ea-89ae-52ff3fce5078.png)
et par magie ...
![image](https://user-images.githubusercontent.com/40739563/73386583-5cc06e80-42cf-11ea-8455-494bfd205a68.png)
(Reading database ... 52458 files and directories currently installed.)
Removing nextdom-common (1.2.0) ...
Enabling site 000-default.
To activate the new configuration, you need to run:
  systemctl reload apache2

je peux le reinstaller, avec apt install -y nextdom-common , c bon . tout fonctionne

2020-01-30 11:23 UTC, Gis70 requested changes
Sur installation vm Buster, en install_git dans /usr/share/nextdom on a un symlink dans /html qui pointe vers lui même.

2020-02-01 08:29 UTC, Esso1-jeedom commented
peut on avoir la procedure d'install car moi cela ne marche pas  . 

wget -qO -   http://debian.nextdom.org/debian/nextdom.gpg.key  | apt-key add -
echo "deb   http://debian.nextdom.org/debian   nextdom main" >/etc/apt/sources.list.d/nextdom.list
apt update
apt -y install nextdom-common
# 
# Créer un répertoire pour y mettre les sources. Ce répertoire doit être accessible par l'utilisateur www-data donc ne pas le mettre dans /root/
mkdir /var/www/nextdomdev && cd /var/www/nextdomdev  
git clone https://github.com/NextDom/nextdom-core.git -b feature/RefactorPostinst .
./install/install_git.sh


root@orangepiplus:/var/www/nextdomdev/install# ./install_git.sh
02/01/20 09:19:37 AM STEP : Preinst -- Prepare and check prerequisites - 0/7
02/01/20 09:19:37 AM INFO : Local needed directories checked
02/01/20 09:19:37 AM INFO : Local mysql server detected
02/01/20 09:19:37 AM INFO : MySQL/MariaDB service started
/etc/php/7.3
02/01/20 09:19:37 AM INFO : PHP detected
02/01/20 09:19:37 AM INFO : Apache2 service started
02/01/20 09:19:37 AM INFO : Cron service started
02/01/20 09:19:37 AM SUCCESS : Prerequisites are checked with success
02/01/20 09:19:37 AM SCRIPT : ============ Starting preinst.sh ============
02/01/20 09:19:37 AM STEP : Preinst -- Generate Assets - 1/7
 >>> Installation dependencies composer

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in /usr/share/php/Composer/Json/JsonFile.php:153
Stack trace:
#0 /usr/share/php/Composer/Factory.php(290): Composer\Json\JsonFile->validateSchema(1)
#1 /usr/share/php/Composer/Factory.php(576): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), './composer.json', false)
#2 /usr/share/php/Composer/Console/Application.php(345): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, false)
#3 /usr/share/php/Composer/Console/Application.php(458): Composer\Console\Application->getComposer(false, false)
#4 /usr/share/php/Composer/Console/Application.php(156): Composer\Console\Application->getPluginCommands()
#5 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),                                              Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/share/php/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run(Object(Symfony in /usr/share/php/Composer/Json/JsonF                                             ile.php on line 153
02/01/20 09:19:37 AM ERROR : error during composer and npm initialize
 > Initialise NPM
 >>> Installation dependencies composer

Fatal error: Uncaught Error: Call to undefined function Composer\Json\json_decode() in /usr/share/php/Composer/Json/JsonFile.php:153
Stack trace:
#0 /usr/share/php/Composer/Factory.php(290): Composer\Json\JsonFile->validateSchema(1)
#1 /usr/share/php/Composer/Factory.php(576): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), './composer.json', false)
#2 /usr/share/php/Composer/Console/Application.php(345): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, false)
#3 /usr/share/php/Composer/Console/Application.php(458): Composer\Console\Application->getComposer(false, false)
#4 /usr/share/php/Composer/Console/Application.php(156): Composer\Console\Application->getPluginCommands()
#5 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),                                              Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /usr/share/php/Composer/Console/Application.php(104): Symfony\Component\Console\Application->run(Object(Symfony in /usr/share/php/Composer/Json/JsonF                                             ile.php on line 153
02/01/20 09:19:37 AM ERROR : error during asset generation
02/01/20 09:19:37 AM INFO : installed nodejs
02/01/20 09:19:37 AM INFO : installed composer manager
02/01/20 09:19:37 AM INFO : installed project dependencies
02/01/20 09:19:37 AM INFO : copied icons, themes and images from assets
02/01/20 09:19:37 AM INFO : generated css files
02/01/20 09:19:37 AM INFO : generated javascript files
02/01/20 09:19:37 AM STEP : Preinst -- Configure MySQL/MariaDB - 2/7
02/01/20 09:19:37 AM INFO : created nextdom mysql configuration: /etc/mysql/conf.d/nextdom_my.cnf
02/01/20 09:19:37 AM SUCCESS : MySQL is configured with success
02/01/20 09:19:37 AM STEP : Preinst -- Prepare /var/www/html- 3/7
02/01/20 09:19:37 AM INFO : warning : directory /var/www/html isn't empty, renamed to /var/www/html.fgfrw8Km
02/01/20 09:19:37 AM SUCCESS : /var/www/html is prepared with success
02/01/20 09:19:37 AM STEP : Preinst -- Configure Apache - 4/7
02/01/20 09:19:37 AM INFO : updated wwwdir in : /etc/apache2/sites-available/nextdom.conf
02/01/20 09:19:37 AM INFO : updated wwwdir in : /etc/apache2/sites-available/nextdom-ssl.conf
02/01/20 09:19:37 AM INFO : updated wwwdir in : /etc/apache2/sites-available/nextdom-common
Generating RSA private key, 2048 bit long modulus (2 primes)
.....................................................................+++++
.................+++++
e is 65537 (0x010001)
Signature ok
subject=C = FR, ST = Paris, L = Paris, O = Global Security, OU = IT Department, CN = example.com
Getting Private key
02/01/20 09:19:37 AM INFO : created SSL self-signed certificates in /etc/nextdom/ssl/
02/01/20 09:19:37 AM SUCCESS : Apache is configured with success
02/01/20 09:19:37 AM STEP : Preinst -- Configure MySQL/MariaDB - 5/7
02/01/20 09:19:37 AM INFO : Writing MariaDb/MySQL information file: /etc/nextdom/mysql/secret
02/01/20 09:19:37 AM SUCCESS : MySQL/MariaDB is configured with success
02/01/20 09:19:37 AM STEP : Preinst -- Generate MySQL/MariaDB structure - 6/7
02/01/20 09:19:37 AM INFO : deleted mysql user: nextdom
02/01/20 09:19:37 AM INFO : created mysql user: nextdom
02/01/20 09:19:37 AM INFO : deleted mysql table: nextdom
02/01/20 09:19:37 AM INFO : created mysql table: nextdom
02/01/20 09:19:37 AM INFO : configured table privileges: nextdom
02/01/20 09:19:37 AM SUCCESS : Database structure generated with success
02/01/20 09:19:37 AM STEP : Preinst -- Configure PHP - 7/7
02/01/20 09:19:37 AM INFO : Directory or file : /var/www/nextdomdev/assets/config/default.config.ini removed
02/01/20 09:19:37 AM INFO : Directory or file : /etc/php/7.3/apache2/conf.d/10-opcache.ini removed
02/01/20 09:19:37 AM INFO : production mode
02/01/20 09:19:37 AM INFO : enable PHP opcache
02/01/20 09:19:37 AM INFO : restart Apache
02/01/20 09:19:37 AM SUCCESS : PHP is configured with success
02/01/20 09:19:37 AM SCRIPT : ============ Preinst.sh is executed ... ============
02/01/20 09:20:03 AM SCRIPT : ============ Starting postinst.sh ============
02/01/20 09:20:03 AM INFO : Apache2 service started
02/01/20 09:20:03 AM INFO : Cron service started
02/01/20 09:20:03 AM INFO : Local mysql server detected
02/01/20 09:20:03 AM INFO : MySQL/MariaDB service started
02/01/20 09:20:03 AM STEP : Postinst -- Create needed files and directories - 1/12
02/01/20 09:20:03 AM INFO : Directory : /var/www/nextdomdev/plugins created
02/01/20 09:20:03 AM INFO : Directory or file : /var/log/nextdom/install.log removed
02/01/20 09:20:03 AM INFO : Directory or file : /tmp/jeedom removed
ln: failed to access '/tmp/jeedom': Permission denied
02/01/20 09:20:03 AM INFO : created temporary directory: /tmp/nextdom
02/01/20 09:20:03 AM SUCCESS : Files and directories are created with success
02/01/20 09:20:03 AM STEP : Postinst -- Prepare directory layout - 2/12
02/01/20 09:20:03 AM INFO : Directory or file : /var/lib/nextdom/config removed
02/01/20 09:20:03 AM INFO : created configuration directory /var/lib/nextdom/config
02/01/20 09:20:03 AM INFO : Directory or file : /var/lib/nextdom/data removed
02/01/20 09:20:03 AM INFO : created data directory /var/lib/nextdom/data
02/01/20 09:20:03 AM INFO : created core configuration symlink: /var/www/nextdomdev/core/config
 [...]

2020-02-02 10:09 UTC, Esso1-jeedom commented
donc c ok pour moi
Armbian buster 
debian Buster
je test cette aprem RPI 9 et 10

2020-02-02 13:09 UTC, merged