Fix du problème d'image sur les designs
NextDom/nextdom-core pull request #1633
Opened 2020-01-06 15:32 UTC by Sylvaner

https://github.com/NextDom/nextdom-core/issues/1565
https://github.com/NextDom/nextdom-core/issues/1566

Tester la suppression et l'ajout d'une image JPG dans les designs

2020-01-06 16:55 UTC, Esso1-jeedom commented
![image](https://user-images.githubusercontent.com/40739563/71833664-b60cf780-30ad-11ea-86f2-684883f95639.png)

2020-01-06 17:09 UTC, Esso1-jeedom commented
aprés la migration d'un backup jeedom, il ne reconnait plus les images en JPG,  backup 3.2.9 de jeedom

2020-01-06 18:24 UTC, iWils requested changes
- Un test a été effectué avec une installation fraiche sans restauration de backup.
Il n'a pas été concluant car lors de l'ajoute d'une image PNG ou JPG, Nextdom me retourne l'erreur suivante:
![image](https://user-images.githubusercontent.com/56263502/71835345-91b31a00-30b1-11ea-84ca-89689b77b4ae.png)

Au niveau du log http.error je retrouve les infos suivantes:
```
[06-Jan-2020 18:08:52 Europe/Berlin] PHP Warning:  mkdir(): No such file or directory in /var/www/html/src/Ajax/PlanAjax.php on line 206
[06-Jan-2020 18:08:52 Europe/Berlin] PHP Warning:  copy(/var/lib/nextdom/data/custom/plans/planHeader1-61a05ed161d968899166ee4ac394ada8c890c7f7bbdb7e95c634e2083615cea284d970b1dd6d6a72b393dac96a3d017f8313a3ad015b2ea0082e6017d05fc08d.jpg): failed to open stream: No such file or directory in /var/www/html/src/Ajax/PlanAjax.php on line 236
[06-Jan-2020 18:09:01 Europe/Berlin] PHP Warning:  mkdir(): No such file or directory in /var/www/html/src/Ajax/PlanAjax.php on line 206
[06-Jan-2020 18:09:01 Europe/Berlin] PHP Warning:  copy(/var/lib/nextdom/data/custom/plans/planHeader1-c744c0b5ff3a2af2c929cb55246cd27229df8ecf0036c308817111d025b0e6e13508a1507d54dd82196c6d47e5f665084c262538ebe9745e77e8c2ce87d758a1.jpg): failed to open stream: No such file or directory in /var/www/html/src/Ajax/PlanAjax.php on line 236
[06-Jan-2020 18:19:45 Europe/Berlin] PHP Warning:  mkdir(): No such file or directory in /var/www/html/src/Ajax/PlanAjax.php on line 206
[06-Jan-2020 18:19:45 Europe/Berlin] PHP Warning:  copy(/var/lib/nextdom/data/custom/plans/planHeader1-4512561bc74be6e337132f8b8576aae6da3affa06598bd9ed1ca808b541badd87799ad4b5a15b01a3fac110359ab714a259a6a4aff39fc5904f2ff970b9c4023.png): failed to open stream: No such file or directory in /var/www/html/src/Ajax/PlanAjax.php on line 236
```

- Test d'ajout de background JPG/PNG **Ok** avec une backup Nextdom

- Test d'ajout de background JPG **Ko** avec une Backup Jeedom OK avec PNG

**Infos:**
Les images sont ajouts avec les droits suivants dans le dossier /var/lib/nextdom/data/custom/plans/:

```
-rw-r--r-- 1 www-data www-data 1638192 janv.  6 18:36 4512561bc74be6e337132f8b8576aae6da3affa06598bd9ed1ca808b541badd87799ad4b5a15b01a3fac110359ab714a259a6a4aff39fc5904f2ff970b9c4023.png
-rw-r--r-- 1 www-data www-data   90605 janv.  6 18:35 61a05ed161d968899166ee4ac394ada8c890c7f7bbdb7e95c634e2083615cea284d970b1dd6d6a72b393dac96a3d017f8313a3ad015b2ea0082e6017d05fc08d.jpg
-rw-r--r-- 1 www-data www-data 1638192 janv.  6 18:36 planHeader1-4512561bc74be6e337132f8b8576aae6da3affa06598bd9ed1ca808b541badd87799ad4b5a15b01a3fac110359ab714a259a6a4aff39fc5904f2ff970b9c4023.png
-rw-r--r-- 1 www-data www-data   90605 janv.  6 18:35 planHeader1-61a05ed161d968899166ee4ac394ada8c890c7f7bbdb7e95c634e2083615cea284d970b1dd6d6a72b393dac96a3d017f8313a3ad015b2ea0082e6017d05fc08d.jpg
```

2020-01-06 18:52 UTC, Sylvaner commented
Bon je vais revoir complètement cette gstion des fonds d'écran

2020-01-06 19:18 UTC, Esso1-jeedom commented
pour la fresh install il manque le rep custom. c'est tout, par defaut nextdom gere les  Jpg/png/ etc... c'est la migration d'un backup au dessus de 3.2.11 qui pose pb et ait que les jpg ne sont pas lu contrairement aun JPEG

2020-01-07 10:51 UTC, Esso1-jeedom commented
pour la partie nextdom , c'est ok , ajout et sup d'image de fond quand le rep custom est existant . 
pour la partie migration : cela ne marche tjrs pas aprés une migration

2020-01-07 22:56 UTC, Sylvaner commented
Problème des droits réglé normalement

2020-01-08 07:09 UTC, Esso1-jeedom approved these changes

2020-01-08 07:09 UTC, Esso1-jeedom commented
c parfait tout marche .

2020-01-08 09:25 UTC, dcjona commented
![image](https://user-images.githubusercontent.com/34706426/71966057-3132f280-3201-11ea-97b5-faf514294f08.png)
sur design , plan, malgré la présence de data/custom

2020-01-08 21:32 UTC, slobberbone requested changes
Idem @dcjona

2020-01-08 22:08 UTC, iWils commented
Problème que @dcjona avec une fresh install et une restauration backup Jeedom.

2020-01-09 08:23 UTC, Esso1-jeedom commented
les versions des backup jeedom ?  deja faudra corriger les repertoire manquant par default 
sur fresh install manque les rep /custom/plans      dans data donc marche pas
aprés l'ajout des rep ca marche 
sur restore backup nextdom  ca marche  j'ajoute et je supprime les fonds.

sur backup jeedom  HS
on peut tjrs mettre du jpeg/png
plus aucune image de la migration est récuperer  .

2020-01-09 08:26 UTC, Esso1-jeedom commented
> 
> 
> ![image](https://user-images.githubusercontent.com/34706426/71966057-3132f280-3201-11ea-97b5-faf514294f08.png)
> sur design , plan, malgré la présence de data/custom

oups  en fait il faut /custom/plans
voila le pb de l'erreur  aprés on a un autre pb . erreur dans la migration 
et plus d'images recuperer

2020-01-09 22:04 UTC, iWils commented
- Test effectué suite à une fresh install sans restauration, en créant le répertoire plans sous l'arborescence /var/lib/nextdom/custom avec les bon droits:
```
NextDom-DEV:/var/lib/nextdom/custom# ll
total 8
drwxr-xr-x 2 www-data www-data 4096 janv.  9 22:30 desktop
drwxr-xr-x 2 www-data www-data 4096 janv.  9 22:40 plans
```
Le problème persiste
![image](https://user-images.githubusercontent.com/56263502/72107433-9c7be200-3331-11ea-9984-8f3cfe45261d.png)
```
NextDom-DEV:/var/lib/nextdom/custom# ll
total 8
drwxr-xr-x 2 www-data www-data 4096 janv.  9 22:30 desktop
drwxr-xr-x 2 www-data www-data 4096 janv.  9 22:40 plans
```
- Test avec la restauration d'une backup Jeedom 3.3.35: 
Message d'erreur similaire que le précédent test

2020-01-10 06:42 UTC, Sylvaner commented
Mauvaise lecture de la doc php, c'est corrigé, merci pour les retours, niquel pour trouver le problème

2020-01-10 07:38 UTC, Esso1-jeedom commented
de mon coté ca fonctionne . attendre la confirmation de iWils .
![image](https://user-images.githubusercontent.com/40739563/72133561-15a32580-3382-11ea-84ef-b349f4ff4a9e.png)

ras sur la migration 
ca marche pour moi

2020-01-10 10:03 UTC, Esso1-jeedom commented
nota  iWils ,  tu as une erreur . le custom et sous data
![image](https://user-images.githubusercontent.com/40739563/72144444-cfa58c00-3398-11ea-8542-ed6439d4a511.png)
toi tu as crée custom au mauvais endroit .

2020-01-10 15:33 UTC, Sylvaner commented
> erreur . le custom et so

C'est quoi ça ? :)

2020-01-10 21:31 UTC, iWils approved these changes
- Test avec un fresh install: OK
- Test avec une backup Jeedom: OK
- Test avec une backup NextDom: OK

vu avec @Esso1-jeedom OK pour validation

2020-01-10 22:27 UTC, Sylvaner commented
Wooohoooo super merci :)

2020-01-14 09:35 UTC, slobberbone approved these changes

2020-01-14 09:35 UTC, merged