Corrige le probleme de 404 sur la version disponible
NextDom/nextdom-core pull request #1635
Opened 2020-01-06 22:06 UTC by ralmn

Fix #1567

2020-01-06 22:18 UTC, slobberbone requested changes
Tu dois garder Common::CORE et non une chaine 'core'

2020-01-06 22:40 UTC, Sylvaner commented
Bonjour, 
Merci pour ta correction, juste quelques petits changements 
 - Nous essayons de remplacer toutes les chaines de caractères par une variable, c'est pour ça que nous mettons Common::CORE plutôt que simplement 'core', cela peut paraitre compliqué pour ce cas mais il y a un réel plus sur la vision globale 
 - Si tu peux, nous avons oublier un \com_http, si tu veux tu peux le changer en ComHttp et donc rajouter 'use NextDom\Com\ComHttp;' en haut du fichier.

Maintenant que t'as mis le doit dessus, il va falloir comprendre comment on a pu passer à côté :)

2020-01-06 22:51 UTC, ralmn commented
Merci pour la review, pour le Common::Core j'ai fait une erreur de copier collé depuis la master :( 
J'ai aussi fait le changement le CommHttp

2020-01-07 22:50 UTC, slobberbone requested changes
je crois que pour la version il faut que tu vises /data/config/Nextdom_version

2020-01-07 22:53 UTC, Sylvaner commented
> je crois que pour la version il faut que tu vises /data/config/Nextdom_version

???

Perso je valide, j'ai testé et ça fonctionne :)

2020-01-07 22:58 UTC, Sylvaner approved these changes

2020-01-08 08:16 UTC, TekiStone reviewed
Hello,
Je vois bien une version apparaître après clique sur vérifier : 
![image](https://user-images.githubusercontent.com/35001669/71961242-40ad3e00-31f7-11ea-870d-3e85594fb468.png)
Par contre l'issue #1567 ne semble pas corrigé intégralement, il reste le soucis du liens vers le changelog qui contient toujours les ".."
Issue : 
![image](https://user-images.githubusercontent.com/35001669/71961359-6df9ec00-31f7-11ea-9600-f59356746774.png)
VM de test : 
![image](https://user-images.githubusercontent.com/35001669/71961407-8407ac80-31f7-11ea-92aa-c5a243933d14.png)

2020-01-08 18:25 UTC, ralmn commented
(désolé j'ai missclick le bouton de demande de re-review)

> je crois que pour la version il faut que tu vises /data/config/Nextdom_version

Hum le `/data/config/Nextdom_version` je le trouve pas dans le repo. Le seul que j'ai trouvé `Nextdom_version` se trouve dans `/assets/config/Nextdom_version`

2020-01-08 21:28 UTC, Gis70 approved these changes
OK je merge Merci.

2020-01-08 21:28 UTC, merged

2020-01-08 21:40 UTC, Gis70 commented
Rejoins nous sur Discord https://discord.gg/aXVQCbN