New WIdget Theme & New Avatars
NextDom/nextdom-core pull request #1645
Opened 2020-01-08 09:55 UTC by cyrilphoenix71

La PR a joute un nouveau theme pour les tuiles du dash, avant on avait (adminlte ou flat), maintenant on a aussi "nextdom"
La PR ajoute aussi une série d'avatar

Pour tester :
- Jouer avec les themes (light/dark/mix) et les themes widget (adminlte/flat/nextdom) en verifiant qu'il n'y a pas de bizarrerie graphique sur le dashboard et un peu partout
- tester les nouveaux avatar

2020-01-08 11:38 UTC, vinceg77 commented
@TesteursFous : vérifier qu'il y a bien un avatar clown, et un avatar kamikaze comme demandé au dev ! :)

2020-01-08 11:58 UTC, TekiStone reviewed
Les nouveaux avatars dont le clown flippant sont la... (il fait vraiment peur...)
![image](https://user-images.githubusercontent.com/35001669/71976387-80cfe900-3216-11ea-9002-50199b599ffb.png)

2020-01-08 17:00 UTC, iWils approved these changes
Tests effectués avec et sans backup : OK
- Les nouveaux avatars sont bien présents
- Les Widgets sont fonctionnels avec tous les thèmes
- Les paramètres des widget sont toujours accessible si on clique sur le titre.
- Le redimensionnement des Widgets est opérationnel

Validé pour ma part

2020-01-09 01:07 UTC, vinceg77 requested changes
Pas  de soucis de manière globale, tout fonctionne.

Cependant lorsqu'au first use on choisit le nouveau theme 'nextdom' il n'est pourtant pas sélectionné lorsqu'on est logué... C'est flat qui est actif par défaut (tout du moins avec le theme 'light' ou 'mix') (testé 2 fois !)

Ce nouveau thème est sympa !
Par contre était ce vraiment nécessaire - outre le coté fun - d'avoir tant d'avatars ??

2020-01-09 20:24 UTC, TekiStone approved these changes

2020-01-09 22:06 UTC, vinceg77 commented
Désolé, après une enième re verification, je m’aperçois que si au first use j'ai choisi le theme widget 'nextdom', j'ai bien le theme widget 'nextdom' sélectionné par défaut lorsque je me logue !
L'habitude de faire un restore systématique m'a joué des tours ....

2020-01-09 22:06 UTC, vinceg77 approved these changes

2020-01-09 22:06 UTC, merged