Fix du bug d'envoi des mails/telegram
NextDom/nextdom-core pull request #1661
Opened 2020-01-17 23:48 UTC by Sylvaner

2020-01-18 00:16 UTC, Gis70 approved these changes
Les photos via camera sont bien envoyés sur telegram au top !

2020-01-18 21:53 UTC, Gis70 requested changes
#1637 ne marche toujours pas telegram ou mail

2020-01-20 08:50 UTC, Sylvaner commented
#1637 n'est plus d'actualité

2020-01-20 09:18 UTC, Gis70 approved these changes

2020-01-20 10:52 UTC, Gis70 commented
Testé sur 3 installation différentes dont une fresh. Testé telegram et mail. Je pense que ça compte pour 2 mini... Sans compter Sylvain. Je merge.

2020-01-20 10:53 UTC, merged