Change ENGINE=`MyISAM` to `InnoDB` for `interactQuery`
NextDom/nextdom-core pull request #1716
Opened 2020-03-24 08:54 UTC by lucguinchard

2020-03-24 09:11 UTC, slobberbone requested changes
Il faut également gérer l'upgrade de cette table :)

2020-03-25 13:08 UTC, Esso1-jeedom commented
comment on test deja ?

2020-03-26 18:10 UTC, Esso1-jeedom commented
nota j'arrive pas a restorer un backup 
![image](https://user-images.githubusercontent.com/40739563/77681290-67c51180-6f95-11ea-8e7b-d85f5a98077b.png)

2020-03-27 08:47 UTC, Esso1-jeedom commented
![image](https://user-images.githubusercontent.com/40739563/77738324-ef4f6680-700f-11ea-93dd-cc479cf177c6.png)

2020-03-27 09:05 UTC, Esso1-jeedom approved these changes

2020-03-27 16:36 UTC, therealcorwin commented
@lucguinchard , sur la table interactQuery je ne pense pas avoir la bonne chose 

`

Table | Create Table
-- | --
interactQuery | CREATE TABLE `interactQuery` (   `id` int(11) NOT NULL AUTO_INCREMENT,   `interactDef_id` int(11) NOT NULL,   `query` text COLLATE utf8_unicode_ci DEFAULT NULL,   `actions` text COLLATE utf8_unicode_ci DEFAULT NULL,   PRIMARY KEY (`id`),   KEY `fk_sarahQuery_sarahDef1_idx` (`interactDef_id`),   FULLTEXT KEY `query` (`query`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

`

2020-03-29 19:17 UTC, lucguinchard commented
Annulation de cette PR pour remplacement https://github.com/NextDom/nextdom-core/pull/1721

2020-03-29 19:17 UTC, closed without merging