gitflow-feature-stash: FixColorPickerPlan
NextDom/nextdom-core pull request #325
Opened 2018-10-16 21:37 UTC by Sylvaner

Fix bug https://github.com/Sylvaner/nextdom-core/issues/319

2018-10-16 22:01 UTC, byackee approved these changes

2018-10-17 07:59 UTC, DanoneKiD requested changes
Pour moi c'est toujours KO. On voit bien le btn avec la couleur, mais il ne réagit pas quand on clique dessus.
![image](https://user-images.githubusercontent.com/522809/47071220-4afaab00-d1f3-11e8-9e83-73fd5a1f4ef0.png)

2018-10-17 09:03 UTC, ColonelMoutarde approved these changes

2018-10-18 05:34 UTC, Sylvaner commented
C'est bon, problème de z-index avec le modal

2018-10-18 05:50 UTC, byackee approved these changes

2018-10-18 07:23 UTC, DanoneKiD approved these changes

2018-10-18 07:23 UTC, merged