fix Issue https://github.com/Sylvaner/nextdom-core/issues/372
NextDom/nextdom-core pull request #378
Opened 2018-10-19 20:13 UTC by byackee

2018-10-19 20:25 UTC, ColonelMoutarde approved these changes

2018-10-20 08:06 UTC, DanoneKiD requested changes
Manque le focus sur l'imput text

2018-10-20 13:28 UTC, byackee commented
Je n'arrive pas a mettre le focus, peut être a cause de bootbox

2018-10-21 13:58 UTC, DanoneKiD approved these changes
Pas grave pour le focus on valide

2018-10-21 13:58 UTC, merged