Fix history page
NextDom/nextdom-core pull request #380
Opened 2018-10-20 12:38 UTC by slobberbone

https://github.com/Sylvaner/nextdom-core/issues/371

2018-10-20 13:47 UTC, byackee requested changes
Tu peux mettre ca en css, en l'ajoutant a une class extstante?

2018-10-21 08:51 UTC, slobberbone commented
@byackee je ne sais pas ce qu'il y a eu, j'ai commité la correction

2018-10-21 09:23 UTC, byackee approved these changes

2018-10-21 16:31 UTC, Sylvaner commented
???
![capture d ecran 2018-10-21 a 18 30 42](https://user-images.githubusercontent.com/957104/47269531-779a2400-d55f-11e8-851f-9308707ab69d.png)

2018-10-21 19:28 UTC, ColonelMoutarde approved these changes

2018-10-21 19:33 UTC, merged