Clean image + liens + new images
NextDom/nextdom-core pull request #406
Opened 2018-10-22 15:59 UTC by cyrilphoenix71

2018-10-22 21:40 UTC, byackee requested changes
Mettre des icônes transparentes pour scénarios et interactions pour que les icones prennent les couleurs du thème

2018-10-23 06:25 UTC, Sylvaner commented
![capture d ecran 2018-10-23 a 08 24 20](https://user-images.githubusercontent.com/957104/47340001-36a82980-d69d-11e8-9cca-49a936c900e8.png)

2018-10-23 09:29 UTC, byackee commented
Nickel 
![image](https://user-images.githubusercontent.com/4707496/47350743-d6be7c80-d6b6-11e8-9acc-14a1fe030dc0.png)

![image](https://user-images.githubusercontent.com/4707496/47350753-de7e2100-d6b6-11e8-86c2-272cb19f9f82.png)

2018-10-23 09:30 UTC, byackee commented
Par contre la c'est pas tres visible 
![image](https://user-images.githubusercontent.com/4707496/47350817-07061b00-d6b7-11e8-97c8-b00feb40eced.png)
![image](https://user-images.githubusercontent.com/4707496/47350832-0ec5bf80-d6b7-11e8-8c98-d904d99712e0.png)

2018-10-23 09:31 UTC, byackee commented
nickel 
![image](https://user-images.githubusercontent.com/4707496/47350894-2f8e1500-d6b7-11e8-9c28-39e10fd61856.png)

2018-10-23 09:32 UTC, byackee commented
Tu peux prévoir un legé bord sur les icones ?
![image](https://user-images.githubusercontent.com/4707496/47351026-6f54fc80-d6b7-11e8-85c0-19d741502748.png)

2018-10-23 09:32 UTC, cyrilphoenix71 commented
@byackee le plugin je le remet comme avant ? et essai avec ma propo core.css

2018-10-23 09:33 UTC, cyrilphoenix71 commented
@byackee tu pourra virer le style border-radius:15px des icones dans les pages scenario, interact etc ?
et remplacer <br> suivi d'un <span> par un <p> ?

2018-10-23 11:40 UTC, byackee approved these changes

2018-10-23 13:46 UTC, ColonelMoutarde approved these changes

2018-10-23 14:08 UTC, merged