Feature/modal to twig
NextDom/nextdom-core pull request #487
Opened 2018-10-29 17:35 UTC by Sylvaner

Première étape du passage des modals sous twig.
Premiers à tester : 
 - A propos
 - La configuration d'une commande

Bien vérifier que les informations soient les mêmes.

2018-10-29 17:36 UTC, Sylvaner commented
https://github.com/Sylvaner/nextdom-core/issues/196

2018-10-30 07:07 UTC, DanoneKiD requested changes
Bug sur les cmd "action" la partie affichage et code se retrouve sous la configuration et pas dans leur tab respective.
Pas de problème sur cmd "info"

2018-10-30 09:46 UTC, DanoneKiD approved these changes

2018-10-30 09:52 UTC, ColonelMoutarde approved these changes

2018-10-30 09:52 UTC, merged