fix log
NextDom/nextdom-core pull request #646
Opened 2018-11-13 14:28 UTC by byackee

fix issues:
https://github.com/Sylvaner/nextdom-core/issues/645
https://github.com/Sylvaner/nextdom-core/issues/644
https://github.com/Sylvaner/nextdom-core/issues/643

2018-11-13 14:44 UTC, ColonelMoutarde requested changes
l'url https://jeedom.nextdom.fr ne fonctionne pas, tu voulais mettre https://jeedom.nextdom.org ? mais elle ne marche pas non plus

2018-11-13 14:46 UTC, byackee commented
Merci c'est une erreur, j'ai corrigé

2018-11-13 14:47 UTC, ColonelMoutarde approved these changes

2018-11-13 15:10 UTC, byackee commented
https://github.com/Sylvaner/nextdom-core/issues/647

2018-11-14 08:34 UTC, Esso1-jeedom approved these changes

2018-11-14 08:55 UTC, merged