fix issue 719 + add interlink btn in page double (param/tools)
NextDom/nextdom-core pull request #722
Opened 2018-11-22 14:14 UTC by cyrilphoenix71

Page scenario :
- fix issue #719 (intellisense in condition and action texte)
- Tweak in theme design of intellisense
- Add scroll

Page Summary, Note, Report, Equipements, Log, Interact :
- add interlink btn (param > tools, tools > param)

TO TEST :
- Navigate in page  Summary, Note, Report, Equipements, Log, Interact (param & tools) + use top-left btns (Parametres, Visualiser)
- Create scenario, use IF bloc, Action bloc with intellisense (write # for conditions, write any letter for action)

2018-11-22 14:16 UTC, ColonelMoutarde requested changes
Tu as des couleurs en dur dans ta css

2018-11-22 21:55 UTC, Esso1-jeedom approved these changes

2018-11-23 05:15 UTC, Esso1-jeedom commented
comme dit, ca fonctionne par contre je suis ps fan du tout des fenetre avec scroll bar
qui affecte tout .
test d'expression
variable 
etc

la lecture sans trouve clairement dégradé .

2018-11-23 11:09 UTC, ColonelMoutarde approved these changes

2018-11-23 13:57 UTC, closed without merging