add autoresize on dashboard
NextDom/nextdom-core pull request #785
Opened 2018-12-10 14:51 UTC by byackee

2018-12-10 15:31 UTC, ColonelMoutarde requested changes
Tu ajoute une balise avec du style. Peux tu le déplacer dans les feuilles de style stp

2018-12-10 15:44 UTC, ColonelMoutarde approved these changes

2018-12-11 09:48 UTC, Esso1-jeedom approved these changes

2018-12-11 20:06 UTC, Esso1-jeedom commented
![bug](https://user-images.githubusercontent.com/40739563/49827942-decb9c00-fd8a-11e8-8df3-6fed3f9ab449.JPG)
on a le transparent qui ne fonctionne pas totalement sur le design.

2018-12-11 22:32 UTC, Sylvaner commented
![capture d ecran 2018-12-11 a 23 32 02](https://user-images.githubusercontent.com/957104/49834569-ff9ced00-fd9c-11e8-9e68-704fbbbb6daa.png)

2018-12-13 08:51 UTC, DanoneKiD approved these changes

2018-12-13 08:51 UTC, merged