Add adminer in dev mode
NextDom/nextdom-core pull request #788
Opened 2018-12-10 16:01 UTC by ColonelMoutarde

2018-12-10 16:55 UTC, cyrilphoenix71 requested changes
Il faudrait ajouter du code qui deplace le php à la racine et le renomme en adminer.php

2018-12-11 08:59 UTC, ColonelMoutarde commented
On perd le système de mise à jour automatique si je fait cela. Tant pis, il sera dans le dossier vendor

2018-12-11 22:38 UTC, Sylvaner commented
Pourquoi faire ?

2018-12-17 06:54 UTC, edgd1er commented
inutile pour docker ou système ou la bdd est déportée. (pr docker, j'ai ajouté adminer comme conteneur séparé pour faire des vérifs rapides dans la bdd.

pour le dev sur vm, pourquoi ne pas installer un gestionnaire extérieur a nextdom ? heidi, workbench, ....

2018-12-17 08:02 UTC, ColonelMoutarde commented
Pour la production, ça n’ Aucun intérêt, c’est pour ça que je l’ai mis dans les dépendances qui sont installé mode dev avec composer

2018-12-17 20:26 UTC, edgd1er approved these changes

2018-12-18 13:08 UTC, byackee approved these changes

2018-12-26 08:46 UTC, cyrilphoenix71 approved these changes

2018-12-26 08:46 UTC, merged