Feature/symfony router
NextDom/nextdom-core pull request #826
Opened 2019-01-11 06:56 UTC by Sylvaner

Implémentation du routeur Symfony

2019-01-18 09:09 UTC, ColonelMoutarde approved these changes

2019-01-18 09:26 UTC, byackee commented
Faut simplement faire un test de fonctionnement général?

Pas de trucs en particulier a tester ?

2019-01-18 09:44 UTC, ColonelMoutarde commented
oui

2019-01-18 09:58 UTC, byackee commented
@Sylvaner pourrais tu merger la develop sur cette branche stp afin de faire des tests plus poussé

Merci

2019-01-20 17:55 UTC, byackee approved these changes

2019-01-20 18:00 UTC, byackee requested changes
![image](https://user-images.githubusercontent.com/4707496/51443209-b28a3000-1ce5-11e9-82b9-59fd7bf42d05.png)

2019-01-21 10:07 UTC, byackee commented
![image](https://user-images.githubusercontent.com/4707496/51467373-b319d980-1d6c-11e9-945d-8218b97239de.png)

2019-01-21 16:56 UTC, byackee approved these changes

2019-01-21 20:58 UTC, merged