Feature/refactoring modales
NextDom/nextdom-core pull request #829
Opened 2019-01-12 12:57 UTC by ColonelMoutarde

2019-01-12 15:22 UTC, Esso1-jeedom commented
je ne vois pas les log des scénario . j'ia vu que ca pour le momnent

2019-01-13 19:05 UTC, perarem commented
Les modales de configuration des éléments d'un design sont vides.
Plus de modales d'ajout de widget ou de courbe dans Vue(s)

2019-01-14 21:05 UTC, perarem commented
> 
> 
> Les modales de configuration des éléments d'un design sont vides.
> Plus de modales d'ajout de widget ou de courbe dans Vue(s)

Plus d'erreurs après les modifs de sylvaner sur ces 2 points.

2019-01-18 08:38 UTC, byackee commented
@ColonelMoutarde tu peux remerger develop stp ?
je suis entrain de tester

2019-01-18 08:58 UTC, ColonelMoutarde commented
Fait

2019-01-18 09:24 UTC, byackee requested changes
- Lors d'un clic sur une commande type info pour afficher la modal historique, rien ne s'affiche

- Manque onglet "affichage" dans la configuration avancée d'une commande

jeedom:
![image](https://user-images.githubusercontent.com/4707496/51377402-186e9000-1b0b-11e9-9bf3-8f8c76d7275c.png)

nextdom:
![image](https://user-images.githubusercontent.com/4707496/51376824-929e1500-1b09-11e9-87d8-6f5ee8f49fe7.png)

- modal "phrases" dans page interaction ne fonctionne pas
![image](https://user-images.githubusercontent.com/4707496/51377057-32f43980-1b0a-11e9-990c-2cdb5a1f2351.png)

voila pour l'instant ce que j'ai trouvé, je continu mes investigations

2019-01-18 10:01 UTC, perarem reviewed
Dans un design, la modale de l'historique d'un composant est vide
![screen shot 01-18-19 at 10 53 am](https://user-images.githubusercontent.com/10147784/51379267-5077d200-1b0f-11e9-930c-a5ac5f4346ca.PNG)

2019-01-18 23:06 UTC, perarem requested changes
Installation d'un plugin du market Jeedom:
- lorsque l'on clic sur un plugin une modale vide apparait.
![screen shot 01-19-19 at 12 04 am](https://user-images.githubusercontent.com/10147784/51417342-d6cafd00-1b7d-11e9-9a58-a9735b6e7166.PNG)

2019-01-19 23:45 UTC, Sylvaner commented
Modale des interactions corrigée

2019-01-20 10:01 UTC, ColonelMoutarde commented
la variable $pageContent n'est pas initialisé. c'est normal ?

2019-01-20 13:48 UTC, Sylvaner commented
Voilà

2019-01-21 09:52 UTC, byackee approved these changes

2019-01-21 12:21 UTC, perarem approved these changes

2019-01-21 19:26 UTC, Sylvaner approved these changes

2019-01-21 19:26 UTC, merged