Feature/fix issue837
NextDom/nextdom-core pull request #843
Opened 2019-01-21 22:09 UTC by Sylvaner

https://github.com/Sylvaner/nextdom-core/issues/837

2019-01-22 08:20 UTC, ColonelMoutarde approved these changes

2019-01-22 11:12 UTC, DanoneKiD requested changes
KO pour moi
Si on ajoute une cmd Info c'est OK mais pas un cmd Action.

2019-01-22 12:31 UTC, cyrilphoenix71 commented
moi c'est ko tout court
avant sauvegarde :
![image](https://user-images.githubusercontent.com/18350629/51535867-031a9e00-1e4a-11e9-914b-e530a852aac0.png)

apres :
![image](https://user-images.githubusercontent.com/18350629/51535880-0ca40600-1e4a-11e9-8cc9-56dd1ee1fedf.png)

2019-01-22 19:01 UTC, Esso1-jeedom commented
pour moi ok avec la dernier modif

2019-01-22 19:01 UTC, Esso1-jeedom approved these changes

2019-01-23 06:06 UTC, DanoneKiD approved these changes

2019-01-23 06:06 UTC, merged