ajout des 3 configs pour des nextdom
NextDom/nextdom-core pull request #85
Opened 2018-09-16 19:21 UTC by edgd1er

par defaut sans acces aux devices
-u avec un accès sur le ttyUSBO
-p avec un accès a tout les devices de l'hote.

2018-09-16 19:44 UTC, byackee approved these changes

2018-09-16 21:10 UTC, Astral0 requested changes
Hello,
Pourrais tu déplacer tes fichier dans /install/OS_specific/Docker et ne pas les mettre à la racine ?
Merci !

2018-09-17 06:18 UTC, edgd1er commented
@byackee  @Astral0 
Bonjour,
J'ai commencé a regarder pour déplacer les fichiers, le problème est que le "context" docker est relatif aux fichiers docker-compose.yml donc install/OS_specific/Docker/. lors de la construction de l'image les fichiers dans install (motd, install.sh, ...) sont hors "context".
Je propose deux solutions: 
*  remettre les fichiers à la racine
* copier les fichiers nécéssaires, temporairement, dans le nouveau context
laquelle préférez vous ?

2018-09-17 12:31 UTC, slobberbone commented
Alors juste pour info, normalement le dockerfile devrait virer et il faudrait utiliser ce dépot : https://github.com/Sylvaner/nextdom-core-test

2018-09-17 19:51 UTC, edgd1er commented
Bonsoir @Astral0  @byackee ,

j'ai tenté le rebase pour avoir un commit propre, pas sur que ce soit le cas. j'ai fait un git rebase --onto origin/develop docker.

2018-09-18 05:39 UTC, edgd1er commented
vue que l'install.sh n'est plus utilisé, je travaille sur une autre façon de créer les conteneurs docker. Cette PR peut etre refusée/annulée.

2018-09-20 14:30 UTC, closed without merging