FixTestsLogAdd
NextDom/nextdom-core pull request #866
Opened 2019-01-29 10:31 UTC by Sylvaner

Amélioration des tests (possibilités de les lancer séparément)
Correction du problème log::add qui faisait planter dans le cas d'un message différents d'une string

2019-01-29 10:32 UTC, ColonelMoutarde requested changes
Il ne faut pas de @, c'est une très mauvaise pratique

2019-01-29 16:30 UTC, Sylvaner commented
Oui mais je vais corriger plus tard, car cette méthode est appelée partout et ce qui m'intéresse surtout c'est les tests.
L'idée pour plus tard, c'est de passer une vérification dans la partie interface, comme ça, ça n'affectera que le code extérieur.

2019-01-30 07:18 UTC, DanoneKiD approved these changes
@ColonelMoutarde Fait une issue pour ce problème pour le corriger par la suite. Y'a bien pire pour l’instant dans le code Jeedom donc...
Je valide, faut avancer ;)

2019-01-30 07:23 UTC, ColonelMoutarde approved these changes

2019-02-01 22:34 UTC, merged