fix js for modals
NextDom/nextdom-core pull request #883
Opened 2019-02-05 14:11 UTC by byackee

fix #836

2019-02-05 16:51 UTC, Sylvaner approved these changes

2019-02-05 17:48 UTC, DanoneKiD requested changes
Ça marche au premier chargement de la page. Si tu fais F5 ça marche plus

2019-02-06 07:49 UTC, byackee commented
voila normalement apres refresh ça fontionne

2019-02-06 08:17 UTC, DanoneKiD approved these changes
Testé OK après fix

2019-02-06 10:11 UTC, ColonelMoutarde approved these changes

2019-02-06 10:11 UTC, merged