fix #527
NextDom/nextdom-core pull request #892
Opened 2019-02-08 09:43 UTC by byackee

permet de filter un widget avec plusieurs categories

2019-02-08 09:45 UTC, byackee commented
fix #527 
#659

2019-02-08 12:31 UTC, Astral0 commented
Après installation de cette PR + restauration d'un backup : 
- le thème Dark sélectionné au FirstUse ne tient pas : après restauration du backup il repasse en blanc
- les prises Tplink du plugin wifismartplug ne sont toujours pas apparentes lorsque l'on filtre "Énergie" avec le FAB (issues 527)
- filtre multi catégories : je vois pas où ? Pour moi le FAB ne permet pas de sélectionner plusieurs icones
- pour l'issue 872, je ne saurais dire si c'est corrigé car je n'ai pas compris la description du bug. Tout ce que je peux dire c'est que l'onglet résumé est dégueu (texte blanc sur fond gris clair) mais que c'est peut être du au passage du thème Dark au thème blanc : 
![image](https://user-images.githubusercontent.com/39194968/52478425-9cb1b180-2ba5-11e9-929d-a1bc5bf56737.png)

2019-02-09 17:31 UTC, Sylvaner requested changes
Comme je le disais, c'est de la faute au plugin, bizarrement, quand on rajoute  data-category="#category#"  dans le template du plugin ça fonctionne...
Le reste c'est du pixel fuck et pas lié

2019-02-14 14:46 UTC, cyrilphoenix71 commented
@Astral0 :
* le fix872 c un bug du pc a @byackee ca n'a rien a voir avec sa PR, donc on en tient pas compte.
* le theme dark c'est corrigé dans une autre PR et ca n'a pas de lien avec cette PR
* la page résumé c pareil.
* le FAB ne permet pas de choisir plusieurs catégorie, l'objet de la PR et de pouvoir cocher plusieurs catégorie sur un équipement et le retrouver dans les 2 filtres sur le dash
> Peux-tu rester cette PR en verifiant ca ?

2019-02-14 15:29 UTC, cyrilphoenix71 approved these changes
ca fonctionne ;)

2019-02-17 17:57 UTC, byackee commented
pourquoi ne pas valider cette pr ?

2019-02-18 10:23 UTC, Sylvaner approved these changes

2019-02-18 13:07 UTC, Astral0 approved these changes

2019-02-18 13:07 UTC, merged