Page scénario
NextDom/nextdom-core pull request #996
Opened 2019-03-19 22:10 UTC by Sylvaner

Amélioration de la lisibilité du code
Correction de bugs (chargement de page)
Optimisations diverses
Passage aux normes i18n

2019-03-20 21:32 UTC, ColonelMoutarde approved these changes

2019-03-20 21:32 UTC, ColonelMoutarde commented
J'ai corrigé les conflicts

2019-03-23 15:58 UTC, Astral0 approved these changes

2019-03-24 19:25 UTC, Gis70 commented
J'ai testé cette version, pas vu de problème sur les scénarios, après je ne sais pas quoi testé exactement pour révéler un défaut.

2019-03-24 19:39 UTC, Gis70 requested changes
Testé OK mais pb sur les Liens : 
![image](https://user-images.githubusercontent.com/16589132/54884769-01cf1700-4e75-11e9-886e-42b4cc9c85ec.png)

2019-03-28 22:15 UTC, slobberbone commented
@Gis70 j'ai corrigé

2019-03-28 23:14 UTC, slobberbone commented
Popup des liens à nouveau fonctionnelle

2019-03-29 09:08 UTC, slobberbone commented
Le bouton Dupliquer ne fonctionne pas.

2019-03-29 09:10 UTC, slobberbone requested changes
Bouton dupliquer HS

2019-03-29 20:29 UTC, Gis70 commented
> Bouton dupliquer HS
OK avec le reste, bouton dupliquer fonctionne mais erreur car le nouveau nom n'est pas pris en compte il prend le même nom que l'ancien j'ai l'impression

2019-03-29 20:30 UTC, Gis70 commented
Bouton variable marche pas non plus !

2019-03-29 20:31 UTC, Gis70 requested changes
bouton dupliquer fonctionne mais erreur car scénario semble avoir pris le même nom que celui dupliqué
Variable marche pas

2019-03-31 20:20 UTC, slobberbone commented
Bouton dupliquer a tester @Gis70

2019-03-31 20:37 UTC, Gis70 commented
ok validé, reste variables qui marche pas

2019-03-31 20:39 UTC, Gis70 approved these changes

2019-03-31 21:00 UTC, slobberbone commented
Bouton variables s'affiche correctement @Gis70 je te laisse valider

2019-03-31 22:09 UTC, slobberbone approved these changes

2019-03-31 22:10 UTC, merged